server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

##网易系(126/163/yeah)邮箱配置
spring:
  mail:
    host: smtp.163.com #发送邮件服务器
    username: fuqiangvn@163.com #发送邮件的邮箱地址
    password: fuqiang0406 #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 994 #465或者994
    from: fuqiangvn@163.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fuqiang?serverTimezone=GMT%2B8
    username: root
    password: yaoyao0203
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    maxWait: 60000
    minIdle: 1 #最小连接池数量
    maxActive: 50 #最大连接池数量
    poolPreparedStatements: false #是否缓存preparedStatement，也就是PSCache，对支持游戏的数据库提升大，mysql建议关闭
    maxOpenPreparedStatements: -1 #要启用PSCache，配置必须大于0
    validationQuery: SELECT 'x' #用来检测连接是否有效的sql，要求是一个查询语句
    testWhileIdle: true #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效(建议配置为true，不影响性能，并且保证安全性)
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    #设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除
    template:
      mandatory: true
      #开启重试机制，默认3次，这里开启为5次
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          #手动确认机制
        acknowledge-mode: manual
    publisher-confirm-type: simple
  mvc:
    static-path-pattern: /static/**

# xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # db-config:
    #id-type: auto #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
    #    field-strategy: NOT_EMPTY #字段策略 IGNORED:"忽略判断" NOT_NULL:"非 NULL 判断") NOT_EMPTY:"非空判断"
    db-type: MYSQL
configuration:
  map-underscore-to-camel-case: true # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射

  #QQ邮箱设置
#  mail:
#    host: smtp.qq.com #发送邮件服务器
#    username: 1016767658@qq.com #发送邮件的邮箱地址
#    password:  ivhkrc*****kbdcf #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
#    properties.mail.smtp.port: 465 #端口号465或587
#    from: 1016767658@qq.com # 发送邮件的地址，和上面username一致
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
#    default-encoding: utf-8

